// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/DriveCommand.h"
#include "Commands/IntakePneumaticsControl.h"
#include "Commands/ShooterControl.h"
#include "Commands/RollerControl.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    gunnerJoystick.reset(new Joystick(1));
    
    driverJoystick.reset(new Joystick(0));
    

    // SmartDashboard Buttons
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    buttonA.reset(new JoystickButton(gunnerJoystick.get(), 0));
    buttonB.reset(new JoystickButton(gunnerJoystick.get(), 1));
    buttonX.reset(new JoystickButton(gunnerJoystick.get(), 2));
    buttonY.reset(new JoystickButton(gunnerJoystick.get(), 3));
    buttonBack.reset(new JoystickButton(gunnerJoystick.get(), 6));
    buttonStart.reset(new JoystickButton(gunnerJoystick.get(), 7));

    buttonA->WhileHeld(new ShooterControl(1, 0)); //forwards
    buttonB->WhileHeld(new ShooterControl(-1, 0)); //backwards
    buttonX->WhenPressed(new IntakePneumaticsControl(true)); //true = extend
    buttonY->WhenPressed(new IntakePneumaticsControl(false)); //false = retract
    buttonStart->WhileHeld(new RollerControl(1, 0)); //suck in
    buttonBack->WhileHeld(new RollerControl(-1, 0)); //suck out
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getdriverJoystick() {
   return driverJoystick;
}

std::shared_ptr<Joystick> OI::getgunnerJoystick() {
   return gunnerJoystick;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
