// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"

class RobotMap {
public:
	static std::shared_ptr<CANTalon> driveBaseSubsystemfrontLeftTalon;
	static std::shared_ptr<CANTalon> driveBaseSubsystemfrontRightTalon;
	static std::shared_ptr<CANTalon> driveBaseSubsystembackLeftTalon;
	static std::shared_ptr<CANTalon> driveBaseSubsystembackRightTalon;
	static std::shared_ptr<RobotDrive> driveBaseSubsystemrobotDrive;

	static std::shared_ptr<CANTalon> shooterSubsystemshooterTalonLeft;
	static std::shared_ptr<CANTalon> shooterSubsystemshooterTalonRight;
	static std::shared_ptr<Servo> shooterSubsystemshooterServo;

	static std::shared_ptr<CANTalon> intakeSubsystemintakeTalon;
	static std::shared_ptr<Servo> intakeSubsystemintakeServo;

	static void init();
};
#endif
